version: '3.8'

name: gameofthree
services:
  # RabbitMQ Message Broker (for game moves)
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # RabbitMQ connection port
      - "15672:15672" # RabbitMQ management UI (http://localhost:15672)

  # Redis (for Player Registration)
  redis:
    image: redis:latest
    container_name: redis1
    restart: always
    ports:
      - "6379:6379"  # Redis default port
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
